cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/versions'

brew 'docker'
brew 'ffmpeg'
brew 'git'
brew 'go'
brew 'gpg'
brew 'gpg-agent'
brew 'grc'
brew 'htop-osx'
brew 'hugo'
brew 'keybase'
brew 'maven'
brew 'node'
brew 'pinentry-mac'
brew 'shellcheck'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'unrar'
brew 'vim', args: ['--override-system-vi']
brew 'wget'
brew 'youtube-dl'
brew 'zsh'

# gnu stuff
brew 'coreutils'
brew 'findutils'
brew 'gnu-tar'
brew 'gnu-sed'
brew 'gawk'
brew 'gnutls'
brew 'gnu-indent'
brew 'gnu-getopt'

# antibody
tap 'getantibody/homebrew-antibody'
brew 'antibody'

# casks
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'

cask 'atom'
cask 'beamer'
cask 'caffeine'
cask 'diffmerge'
cask 'font-hack'
cask 'franz'
cask 'google-chrome'
cask 'google-drive'
cask 'istat-menus'
cask 'iterm2'
cask 'java' unless system '/usr/libexec/java_home --failfast'
cask 'java7'
cask 'slack'
cask 'slate'
cask 'spotify'
cask 'telegram'
cask 'the-unarchiver'
cask 'utorrent'
cask 'viscosity'
cask 'vlc'
cask 'rescuetime'

# https://github.com/sindresorhus/quick-look-plugins
cask 'betterzipql'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'suspicious-package'
cask 'webpquicklook'
