cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"

tap "1password/tap"
tap "github/gh"
tap "hashicorp/tap"
tap "jesseduffield/lazygit"
tap "jorgelbg/tap"
tap "marcel-dias/tap"

brew "ansible"
brew "argocd"
brew "colima"
brew "marcel-dias/tap/antibody"
brew "aws-iam-authenticator"
brew "awscli"
brew "gettext"
brew "diff-so-fancy"
brew "docker-credential-helper"
brew "ffmpeg"
brew "gettext"
brew "gh"
brew "git"
brew "go"
brew "graphviz"
brew "grc"
brew "helm"
brew "highlight"
brew "htop"
brew "jq"
brew "k3d"
brew "kind"
brew "kubectx"
brew "kustomize"
brew "kubectx"
brew "lazygit"
brew "mas"
brew "shellcheck"
brew "starship"
brew "telnet"
brew "terminal-notifier"
brew "tfenv"
brew "tflint"
brew "vim"
brew "wget"
brew "yq"
brew "zsh"
brew "zsh-async"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-async"
brew "zsh-async"
brew "zsh-fast-syntax-highlighting"
brew "zsh-history-substring-search"

cask "1password"
cask "1password/tap/1password-cli"
cask "brave-browser"
cask "docker"
cask "font-hack"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "gpg-suite-no-mail"
cask "intellij-idea-ce"
cask "istat-menus"
cask "iterm2"
cask "lens"
cask "rescuetime"
cask "spotify"
cask "visual-studio-code"

# MacApp Store Apps
mas "Amphetamine", id: 937984704
mas "Magnet", id: 441258766
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
